apiVersion: k0s.k0sproject.io/v1beta1
kind: ClusterConfig
metadata:
  name: k0s
spec:
  extensions:
    helm:
      repositories:
      - name: openebs
        url: https://openebs.github.io/openebs
      charts:
      - name: openebs
        chartname: openebs/openebs
        version: "4.5.1"
        namespace: openebs
        order: 1
        values: |
          engines:
            local:
              lvm:
                enabled: false
              zfs:
                enabled: false
            replicated:
              mayastor:
                enabled: false
          loki:
            enabled: false
          alloy:
            enabled: false
          localpv-provisioner:
            hostpathClass:
              enabled: true
              isDefaultClass: true
